#

In [49]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [50]:
df_climbers = pd.read_csv("data/8a/climber_df.csv")
df_grades_conversion = pd.read_csv("data/8a/grades_conversion_table.csv")
df_routes = pd.read_csv("data/8a/routes_rated.csv")

In [51]:
display(df_climbers.info())
display(df_climbers.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10927 entries, 0 to 10926
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       10927 non-null  int64
 1   country       10927 non-null  object
 2   sex           10927 non-null  int64
 3   height        10927 non-null  int64
 4   weight        10927 non-null  int64
 5   age           10927 non-null  float64
 6   years_cl      10927 non-null  int64
 7   date_first    10927 non-null  object
 8   date_last     10927 non-null  object
 9   grades_count  10927 non-null  int64
 10  grades_first  10927 non-null  int64
 11  grades_last   10927 non-null  int64
 12  grades_max    10927 non-null  int64
 13  grades_mean   10927 non-null  float64
 14  year_first    10927 non-null  int64
 15  year_last     10927 non-null  int64
dtypes: float64(2), int64(11), object(3)
memory usage: 1.3+ MB

None

,user_id,country,sex,height,weight,age,years_cl,date_first,date_last,grades_count,grades_first,grades_last,grades_max,grades_mean,year_first,year_last
0,1,SWE,0,177,73,41.0,21,1999-02-06 23:00:00,2001-07-31 22:00:00,84,36,55,62,46.750000,1999,2001
1,3,SWE,0,180,78,44.0,22,1999-03-31 22:00:00,2000-07-19 22:00:00,12,53,51,59,52.833333,1999,2000
2,4,SWE,1,165,58,33.0,16,2004-06-30 22:00:00,2009-05-26 22:00:00,119,53,49,64,53.890756,2004,2009
3,10,SWE,0,167,63,52.0,25,2000-01-14 23:00:00,2017-06-01 22:00:00,298,53,49,63,49.406040,2000,2017
4,16,NOR,0,177,68,44.0,21,1998-02-27 23:00:00,2010-05-13 22:00:00,5,53,49,53,51.400000,1998,2010

In [52]:
display(df_routes.info())
display(df_routes.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55858 entries, 0 to 55857
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          55858 non-null  int64
 1   name_id             55858 non-null  int64
 2   country             55858 non-null  object
 3   crag                55858 non-null  object
 4   sector              55858 non-null  object
 5   name                55858 non-null  object
 6   tall_recommend_sum  55858 non-null  int64
 7   grade_mean          55858 non-null  float64
 8   cluster             55858 non-null  int64
 9   rating_tot          55858 non-null  float64
dtypes: float64(2), int64(4), object(4)
memory usage: 4.3+ MB

None

,Unnamed: 0,name_id,country,crag,sector,name,tall_recommend_sum,grade_mean,cluster,rating_tot
0,0,0,and,montserrat,prohibitivo,diagonal de la x,-1,49.250000,3,-0.045211
1,1,1,and,montserrat,prohibitivo,mehir,-1,49.000000,2,0.116464
2,2,2,and,montserrat,prohibitivo,pas de la discordia,0,49.000000,2,0.178722
3,3,3,and,tartareu,bombo suis,tenedor libre,0,44.333333,3,0.158449
4,4,4,arg,bandurrias,rincon,tendinitis,1,48.500000,0,0.075797

In [53]:
display(df_grades_conversion.info())
display(df_grades_conversion.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  85 non-null     int64
 1   grade_id    85 non-null     int64
 2   grade_fra   85 non-null     object
dtypes: int64(2), object(1)
memory usage: 2.1+ KB

None

   Unnamed: 0  grade_id grade_fra
0           0         0         -
1           1         1         -
2           2         2         -
3           3         3         1
4           4         4        1a

In [54]:
df_climbers = df_climbers.drop(['years_cl', 'date_first', 'date_last'], axis=1)
df_climbers['age'] = df_climbers['age'].astype(int)

df_routes = df_routes.drop(['Unnamed: 0', 'cluster', 'tall_recommend_sum', 'rating_tot'], axis=1)
df_routes['grade_mean'] = [round(grade) for grade in df_routes['grade_mean']]
df_routes['grade_mean'] = df_routes['grade_mean'].astype(int)
df_routes.rename(columns={
    'grade_mean': 'grade_id',
    'name' : 'route'},
    inplace=True)
df_routes['country'] = df_routes['country'].str.upper()

df_grades_conversion = df_grades_conversion.drop(['Unnamed: 0'], axis=1)
df_grades_conversion = df_grades_conversion[df_grades_conversion['grade_id']>=3]

In [55]:
print("Number of unique climbers: ", len(df_climbers['user_id'].unique()))
print("Number of unique routes: ", len(df_routes['name_id'].unique()))
print("Number of unique grades: ", len(df_grades_conversion['grade_fra'].unique()))
print("Number of route countries: ", len(df_routes['country'].unique()))
print("Number of climbers home countries: ", len(df_climbers['country'].unique()))

Number of unique climbers:  10927
Number of unique routes:  55858
Number of unique grades:  82
Number of route countries:  59
Number of climbers home countries:  26

In [56]:
display(len(df_climbers[df_climbers['grades_count']==0]))
display(len(df_climbers[df_climbers['age']<10]))
display(len(df_climbers[df_climbers['weight']<40]))
display(len(df_climbers[df_climbers['height']<120]))

0

0

0

0

In [57]:
df_routes = pd.merge(df_routes, df_grades_conversion, on = 'grade_id')
df_routes = df_routes.drop(['grade_id'], axis = 1)

In [58]:
df_climbing_history = pd.read_csv("climbing_history_clean.csv")

In [59]:
display(df_climbing_history.info())
display(df_climbing_history.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10357 entries, 0 to 10356
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   climber                    10357 non-null  object
 1   ascent_date                9103 non-null   object
 2   suggested_grade            1194 non-null   object
 3   link                       10357 non-null  object
 4   route                      10357 non-null  object
 5   official_grade             10357 non-null  object
 6   parsed_dates               8888 non-null   object
 7   climbing_style             10357 non-null  object
 8   weight                     9970 non-null   object
 9   date                       8886 non-null   object
 10  year                       8886 non-null   float64
 11  official_grade_consistent  10357 non-null  object
dtypes: float64(1), object(11)
memory usage: 971.1+ KB

None

,climber,ascent_date,suggested_grade,link,route,official_grade,parsed_dates,climbing_style,weight,date,year,official_grade_consistent
0,James Pearson,5th Sep 2006,NaN,/climb/167/keen-roof,Keen Roof,8a+,05-09-2006,Boulder,worked,2006-05-09,2006.0,8a+
1,Dave Nodden,May 2009,NaN,/climb/167/keen-roof,Keen Roof,8a+,19-05-2009,Boulder,worked,2009-05-19,2009.0,8a+
2,Ignacio Sánchez González,4th May 2009,NaN,/climb/167/keen-roof,Keen Roof,8a+,04-05-2009,Boulder,worked,2009-04-05,2009.0,8a+
3,Rupert Davies,8th May 2010,NaN,/climb/167/keen-roof,Keen Roof,8a+,08-05-2010,Boulder,worked,2010-08-05,2010.0,8a+
4,Dawid Skoczylas,11th Sep 2010,NaN,/climb/167/keen-roof,Keen Roof,8a+,11-09-2010,Boulder,worked,2010-11-09,2010.0,8a+

In [60]:
df_climbing_history['route'] = df_climbing_history['route'].str.lower()

In [61]:
df_climbing_history_merge = pd.merge(df_routes, df_climbing_history, on = 'route')
df_climbing_history_merge = df_climbing_history_merge.drop(['link', 'parsed_dates', 'date', 'name_id', 'official_grade', 'ascent_date'], axis = 1)

In [62]:
display(df_climbing_history_merge.info())
display(df_climbing_history_merge.head(20))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3555 entries, 0 to 3554
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country                    3555 non-null   object
 1   crag                       3555 non-null   object
 2   sector                     3555 non-null   object
 3   route                      3555 non-null   object
 4   grade_fra                  3555 non-null   object
 5   climber                    3555 non-null   object
 6   suggested_grade            327 non-null    object
 7   climbing_style             3555 non-null   object
 8   weight                     3450 non-null   object
 9   year                       3070 non-null   float64
 10  official_grade_consistent  3555 non-null   object
dtypes: float64(1), object(10)
memory usage: 305.6+ KB

None

,country,crag,sector,route,grade_fra,climber,suggested_grade,climbing_style,weight,year,official_grade_consistent
0,ARG,covisal,cueva,sauron,8a+,James McHaffie,NaN,Lead,worked,2008.0,8b
1,AUS,blue mountains,bell,event horizon,7c,Jonathan Siegrest,9b,Lead,worked,2022.0,9b
2,AUS,blue mountains,bell,event horizon,7c,Andy Lamb,NaN,Boulder,worked,2024.0,8c+
3,AUS,blue mountains,centenial glen,better than life,8b+/8c,Garth Miller,NaN,Lead,onsight,NaN,8b+
4,AUS,blue mountains,centenial glen,jaws,6b+,Dave Graham,NaN,Lead,worked,NaN,8c
5,AUS,blue mountains,centenial glen,tsunami,8a/+,Aidan Roberts,NaN,Boulder,flash,2016.0,8a
6,AUS,blue mountains,centenial glen,tsunami,8a/+,Molly Thompson-Smith,NaN,Boulder,worked,2017.0,8a
7,AUS,blue mountains,centenial glen,tsunami,8a/+,Frances Bensley,NaN,Boulder,worked,2021.0,8a
8,AUS,blue mountains,centenial glen,tsunami,8a/+,Gracie Martin,NaN,Boulder,worked,2022.0,8a
9,AUS,blue mountains,centenial glen,tsunami,8a/+,Hazel Dearlove,NaN,Boulder,worked,2022.0,8a
10,AUS,blue mountains,centenial glen,tsunami,8a/+,Tara Hayes,NaN,Boulder,worked,2023.0,8a
11,AUS,blue mountains,centenial glen,tsunami,8a/+,Michaela Tracy,NaN,Boulder,worked,2024.0,8a
12,AUS,blue mountains,centenial glen,tsunami,8a/+,Sam Clarke,NaN,Lead,worked,2024.0,8c
13,AUS,blue mountains,centenial glen,tsunami,8a/+,Thilo Schröter,NaN,Boulder,worked,2024.0,8c+
14,AUS,blue mountains,dam cliffs,siesta,7a/+,Noé Looser,NaN,Lead,worked,2020.0,8c
15,AUS,blue mountains,dam cliffs,war and peace,7b,Pat Littlejohn,NaN,Alternate Leads,onsight,1997.0,7b+
16,AUS,blue mountains,dam cliffs,war and peace,7b,Steve Sustad,NaN,Alternate Leads,onsight,1997.0,7b+
17,AUS,blue mountains,dam cliffs,war and peace,7b,Mick Lovatt,NaN,Alternate Leads,onsight,NaN,7b+
18,AUS,blue mountains,dam cliffs,war and peace,7b,Nick Bullock,NaN,Alternate Leads,onsight,NaN,7b+
19,AUS,blue mountains,diamond falls,grey area,8c/+,Garth Miller,NaN,Lead,worked,2000.0,8c